package com.sien.lib.datapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sien.lib.datapp.beans.AimItemVO;
import com.sien.lib.datapp.beans.AimTypeVO;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aimTypeVODaoConfig;

    private final AimTypeVODao aimTypeVODao;

    private final DaoConfig aimItemVODaoConfig;

    private final AimItemVODao aimItemVODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aimTypeVODaoConfig = daoConfigMap.get(AimTypeVODao.class).clone();
        aimTypeVODaoConfig.initIdentityScope(type);

        aimTypeVODao = new AimTypeVODao(aimTypeVODaoConfig, this);

        registerDao(AimTypeVO.class, aimTypeVODao);

        aimItemVODaoConfig = daoConfigMap.get(AimItemVODao.class).clone();
        aimItemVODaoConfig.initIdentityScope(type);

        aimItemVODao = new AimItemVODao(aimItemVODaoConfig, this);

        registerDao(AimItemVO.class, aimItemVODao);
    }
    
    public void clear() {
        aimTypeVODaoConfig.clearIdentityScope();
    }

    public AimTypeVODao getAimTypeVODao() {
        return aimTypeVODao;
    }

    public AimItemVODao getAimItemVODao() {
        return aimItemVODao;
    }
}
